name: Production (master)

on:
  push:
    branches:
      - master

env:
  CLOUDFLARE_PROJECT_NAME: sounddeck

jobs:
  build:
    name: 'Build & Deploy'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: pages deploy dist --project-name="${{ env.CLOUDFLARE_PROJECT_NAME }}"
